/**
 * SentencePiece Tokenizer Parity Tests
 *
 * Tests our TypeScript SentencePiece implementation against golden fixtures
 * generated by Python sentencepiece library.
 */

import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { loadSentencePieceTokenizer } from '../src/sentencepiece/index.js';
import type { SentencePieceTokenizer } from '../src/sentencepiece/index.js';

interface EncodeFixture {
  input: string;
  expected_ids: number[];
  expected_pieces: string[];
}

interface DecodeFixture {
  input_ids: number[];
  expected: string;
}

interface RoundtripFixture {
  original: string;
  encoded: number[];
  decoded: string;
  roundtrip_ok: boolean;
}

interface GoldenFixtures {
  model_name: string;
  model_path: string;
  vocab_size: number;
  special_tokens: {
    unk_id: number;
    bos_id: number;
    eos_id: number;
    pad_id: number;
  };
  encode_fixtures: EncodeFixture[];
  decode_fixtures: DecodeFixture[];
  roundtrip_fixtures: RoundtripFixture[];
}

// Model configurations for testing
const MODELS = [
  {
    name: 't5',
    fixtureFile: 't5-golden.json',
    modelFile: 't5-tokenizer.model',
  },
  {
    name: 'albert',
    fixtureFile: 'albert-golden.json',
    modelFile: 'albert-tokenizer.model',
  },
  {
    name: 'xlnet',
    fixtureFile: 'xlnet-golden.json',
    modelFile: 'xlnet-tokenizer.model',
  },
];

// Utility to escape text for display
function escapeText(text: string, maxLen = 40): string {
  const truncated = text.length > maxLen ? text.slice(0, maxLen) + '...' : text;
  return truncated
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
}

describe('SentencePiece tokenizer - Python sentencepiece parity', () => {
  for (const modelConfig of MODELS) {
    const fixturesPath = join(__dirname, 'fixtures', modelConfig.fixtureFile);
    const modelPath = join(__dirname, '.models', modelConfig.modelFile);

    // Skip if fixtures or model files don't exist
    if (!existsSync(fixturesPath)) {
      describe.skip(`${modelConfig.name} (fixtures not found)`, () => {
        it('skipped', () => {});
      });
      continue;
    }

    if (!existsSync(modelPath)) {
      describe.skip(`${modelConfig.name} (model not found)`, () => {
        it('skipped', () => {});
      });
      continue;
    }

    describe(`model: ${modelConfig.name}`, () => {
      let tokenizer: SentencePieceTokenizer;
      let fixtures: GoldenFixtures;

      beforeAll(async () => {
        fixtures = JSON.parse(readFileSync(fixturesPath, 'utf-8'));
        tokenizer = await loadSentencePieceTokenizer({ modelPath });
      });

      it('has correct vocab size', () => {
        expect(tokenizer.vocabSize).toBe(fixtures.vocab_size);
      });

      describe('encode parity', () => {
        // Load fixtures synchronously for test generation
        const testFixtures: GoldenFixtures = JSON.parse(readFileSync(fixturesPath, 'utf-8'));

        for (const fixture of testFixtures.encode_fixtures) {
          const displayText = escapeText(fixture.input);

          it(`encode("${displayText}") => ${fixture.expected_ids.length} tokens`, async () => {
            // Load tokenizer fresh for this test
            const tok = await loadSentencePieceTokenizer({ modelPath });
            const tokens = tok.encode(fixture.input);
            expect(tokens).toEqual(fixture.expected_ids);
          });
        }
      });

      describe('decode parity', () => {
        const testFixtures: GoldenFixtures = JSON.parse(readFileSync(fixturesPath, 'utf-8'));

        for (const fixture of testFixtures.decode_fixtures) {
          const tokenCount = fixture.input_ids.length;
          const displayExpected = escapeText(fixture.expected);

          it(`decode([${tokenCount} tokens]) => "${displayExpected}"`, async () => {
            const tok = await loadSentencePieceTokenizer({ modelPath });
            const decoded = tok.decode(fixture.input_ids);
            expect(decoded).toBe(fixture.expected);
          });
        }
      });

      describe('roundtrip', () => {
        const testFixtures: GoldenFixtures = JSON.parse(readFileSync(fixturesPath, 'utf-8'));

        // Only test cases that should roundtrip successfully
        const roundtripOk = testFixtures.roundtrip_fixtures.filter((f) => f.roundtrip_ok);

        for (const fixture of roundtripOk) {
          const displayText = escapeText(fixture.original);

          it(`roundtrip("${displayText}")`, async () => {
            const tok = await loadSentencePieceTokenizer({ modelPath });
            const tokens = tok.encode(fixture.original);
            const decoded = tok.decode(tokens);
            expect(decoded).toBe(fixture.decoded);
          });
        }
      });
    });
  }
});

// Edge case tests
describe('SentencePiece tokenizer - edge cases', () => {
  const modelPath = join(__dirname, '.models', 't5-tokenizer.model');

  // Skip if model not available
  const modelExists = existsSync(modelPath);

  describe.skipIf(!modelExists)('empty and whitespace handling', () => {
    it('handles empty string', async () => {
      const tokenizer = await loadSentencePieceTokenizer({ modelPath });
      const tokens = tokenizer.encode('');
      expect(Array.isArray(tokens)).toBe(true);
      expect(tokens.length).toBeGreaterThanOrEqual(0);
    });

    it('handles single space', async () => {
      const tokenizer = await loadSentencePieceTokenizer({ modelPath });
      const tokens = tokenizer.encode(' ');
      expect(Array.isArray(tokens)).toBe(true);
    });

    it('handles multiple spaces', async () => {
      const tokenizer = await loadSentencePieceTokenizer({ modelPath });
      const tokens = tokenizer.encode('   ');
      expect(Array.isArray(tokens)).toBe(true);
    });
  });

  describe.skipIf(!modelExists)('unicode handling', () => {
    it('handles emoji', async () => {
      const tokenizer = await loadSentencePieceTokenizer({ modelPath });
      const tokens = tokenizer.encode('Hello 🌍 World');
      expect(Array.isArray(tokens)).toBe(true);
      expect(tokens.length).toBeGreaterThan(0);
    });

    it('handles ZWJ sequences', async () => {
      const tokenizer = await loadSentencePieceTokenizer({ modelPath });
      // Family emoji with ZWJ
      const tokens = tokenizer.encode('\u{1F468}\u200D\u{1F469}\u200D\u{1F467}\u200D\u{1F466}');
      expect(Array.isArray(tokens)).toBe(true);
    });

    it('handles Japanese text', async () => {
      const tokenizer = await loadSentencePieceTokenizer({ modelPath });
      const tokens = tokenizer.encode('こんにちは世界');
      expect(Array.isArray(tokens)).toBe(true);
      expect(tokens.length).toBeGreaterThan(0);
    });

    it('handles Chinese text', async () => {
      const tokenizer = await loadSentencePieceTokenizer({ modelPath });
      const tokens = tokenizer.encode('你好世界');
      expect(Array.isArray(tokens)).toBe(true);
      expect(tokens.length).toBeGreaterThan(0);
    });

    it('handles combining characters', async () => {
      const tokenizer = await loadSentencePieceTokenizer({ modelPath });
      // cafe with combining acute accent
      const tokens = tokenizer.encode('cafe\u0301');
      expect(Array.isArray(tokens)).toBe(true);
    });
  });

  describe.skipIf(!modelExists)('special token text handling', () => {
    it('handles text that looks like BOS token', async () => {
      const tokenizer = await loadSentencePieceTokenizer({ modelPath });
      const tokens = tokenizer.encode('<s>');
      expect(Array.isArray(tokens)).toBe(true);
    });

    it('handles text that looks like EOS token', async () => {
      const tokenizer = await loadSentencePieceTokenizer({ modelPath });
      const tokens = tokenizer.encode('</s>');
      expect(Array.isArray(tokens)).toBe(true);
    });

    it('handles text with embedded special-looking tokens', async () => {
      const tokenizer = await loadSentencePieceTokenizer({ modelPath });
      const tokens = tokenizer.encode('Start <s> middle </s> end');
      expect(Array.isArray(tokens)).toBe(true);
      expect(tokens.length).toBeGreaterThan(0);
    });
  });

  describe.skipIf(!modelExists)('decode edge cases', () => {
    it('decodes empty token array', async () => {
      const tokenizer = await loadSentencePieceTokenizer({ modelPath });
      const decoded = tokenizer.decode([]);
      expect(decoded).toBe('');
    });

    it('decodes single token', async () => {
      const tokenizer = await loadSentencePieceTokenizer({ modelPath });
      // Token 0 is often <unk> or <s>
      const decoded = tokenizer.decode([1]);
      expect(typeof decoded).toBe('string');
    });
  });
});
