/**
 * Codegen script to download tiktoken vocabulary files and generate
 * TypeScript modules for each encoding.
 *
 * Usage: npx tsx scripts/codegen/encodings.ts
 *
 * This script:
 * 1. Downloads .tiktoken files from OpenAI's public storage
 * 2. Verifies SHA-256 hashes against expected values
 * 3. Parses the base64-encoded vocabulary data
 * 4. Generates TypeScript modules in src/encodings/generated/
 */

import { createHash } from 'node:crypto';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = join(__dirname, '../../src/encodings/generated');

/**
 * Encoding configurations with URLs and expected SHA-256 hashes.
 * Hashes are from tiktoken_ext/openai_public.py
 */
const ENCODINGS = {
  r50k_base: {
    url: 'https://openaipublic.blob.core.windows.net/encodings/r50k_base.tiktoken',
    hash: '306cd27f03c1a714eca7108e03d66b7dc042abe8c258b44c199a7ed9838dd930',
  },
  p50k_base: {
    url: 'https://openaipublic.blob.core.windows.net/encodings/p50k_base.tiktoken',
    hash: '94b5ca7dff4d00767bc256fdd1b27e5b17361d7b8a5f968547f9f23eb70d2069',
  },
  cl100k_base: {
    url: 'https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken',
    hash: '223921b76ee99bde995b7ff738513eef100fb51d18c93597a113bcffe865b2a7',
  },
  o200k_base: {
    url: 'https://openaipublic.blob.core.windows.net/encodings/o200k_base.tiktoken',
    hash: '446a9538cb6c348e3516120d7c08b09f57c36495e2acfffe59a5bf8b0cfb1a2d',
  },
} as const;

type EncodingName = keyof typeof ENCODINGS;

/**
 * Compute SHA-256 hash of data.
 */
function computeSha256(data: Buffer): string {
  return createHash('sha256').update(data).digest('hex');
}

/**
 * Check if bytes are valid UTF-8.
 */
function isValidUtf8(bytes: Uint8Array): boolean {
  try {
    new TextDecoder('utf-8', { fatal: true }).decode(bytes);
    return true;
  } catch {
    return false;
  }
}

/**
 * Convert bytes to a string representation for the generated file.
 * Uses string if valid UTF-8, otherwise uses number array.
 */
function bytesToJsValue(bytes: Uint8Array): string {
  if (isValidUtf8(bytes)) {
    // Convert to string using latin1 to preserve byte values
    let str = '';
    for (let i = 0; i < bytes.length; i++) {
      str += String.fromCharCode(bytes[i]);
    }
    // Escape for JavaScript string literal
    return JSON.stringify(str);
  } else {
    // Use number array
    return `[${Array.from(bytes).join(',')}]`;
  }
}

/**
 * Parse a tiktoken file and return vocabulary entries.
 */
function parseTiktokenFile(content: string): Array<{ rank: number; bytes: Uint8Array }> {
  const entries: Array<{ rank: number; bytes: Uint8Array }> = [];

  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    const parts = trimmed.split(' ');
    if (parts.length !== 2) {
      throw new Error(`Invalid line format: ${line}`);
    }

    const [base64Token, rankStr] = parts;
    const rank = parseInt(rankStr, 10);

    if (isNaN(rank)) {
      throw new Error(`Invalid rank: ${rankStr}`);
    }

    // Decode base64 to bytes
    const bytes = Buffer.from(base64Token, 'base64');
    entries.push({ rank, bytes: new Uint8Array(bytes) });
  }

  return entries;
}

/**
 * Generate TypeScript module content for an encoding.
 */
function generateModule(
  encoding: EncodingName,
  entries: Array<{ rank: number; bytes: Uint8Array }>,
  hash: string
): string {
  // Sort by rank to ensure correct indexing
  entries.sort((a, b) => a.rank - b.rank);

  // Find max rank to determine array size
  const maxRank = entries[entries.length - 1].rank;

  // Build a sparse vocabulary array (fill gaps with null placeholder)
  // Gaps are typically where special tokens go
  const vocabArray: (string | null)[] = new Array(maxRank + 1).fill(null);

  for (const entry of entries) {
    vocabArray[entry.rank] = bytesToJsValue(entry.bytes);
  }

  // Convert nulls to empty string placeholders (special token slots)
  const vocabEntries = vocabArray.map((v) => v ?? '""');

  // Generate the file content
  const lines = [
    '/**',
    ` * Generated vocabulary for ${encoding} encoding.`,
    ' *',
    ' * DO NOT EDIT - This file is auto-generated by scripts/codegen/encodings.ts',
    ' *',
    ` * Source: ${ENCODINGS[encoding].url}`,
    ` * SHA-256: ${hash}`,
    ` * Vocabulary entries: ${entries.length}`,
    ` * Max rank: ${maxRank}`,
    ' */',
    '',
    `import type { TokenVocabulary } from '../../bpe/types.js';`,
    '',
    '/**',
    ` * Vocabulary for ${encoding} encoding.`,
    ' * Index = token rank, value = token bytes (string or number array).',
    ' */',
    `export const VOCAB: TokenVocabulary = [`,
  ];

  // Add vocabulary entries (split into chunks for readability)
  const CHUNK_SIZE = 100;
  for (let i = 0; i < vocabEntries.length; i += CHUNK_SIZE) {
    const chunk = vocabEntries.slice(i, Math.min(i + CHUNK_SIZE, vocabEntries.length));
    lines.push(`  ${chunk.join(',')},`);
  }

  lines.push('];');
  lines.push('');

  return lines.join('\n');
}

/**
 * Download and process a single encoding.
 */
async function processEncoding(encoding: EncodingName): Promise<void> {
  const config = ENCODINGS[encoding];
  console.log(`Processing ${encoding}...`);

  // Download the file
  console.log(`  Downloading from ${config.url}`);
  const response = await fetch(config.url);

  if (!response.ok) {
    throw new Error(`Failed to download ${encoding}: ${response.status}`);
  }

  const buffer = Buffer.from(await response.arrayBuffer());

  // Verify hash
  const actualHash = computeSha256(buffer);
  if (actualHash !== config.hash) {
    throw new Error(
      `Hash mismatch for ${encoding}:\n` +
        `  Expected: ${config.hash}\n` +
        `  Actual:   ${actualHash}`
    );
  }
  console.log(`  Hash verified: ${actualHash.slice(0, 16)}...`);

  // Parse the file
  const content = buffer.toString('utf-8');
  const entries = parseTiktokenFile(content);
  console.log(`  Parsed ${entries.length} tokens`);

  // Generate the module
  const moduleContent = generateModule(encoding, entries, actualHash);

  // Write the file
  const outputPath = join(OUTPUT_DIR, `${encoding}.ts`);
  writeFileSync(outputPath, moduleContent, 'utf-8');
  console.log(`  Written to ${outputPath}`);
}

/**
 * Generate p50k_edit module (reuses p50k_base vocab).
 */
function generateP50kEdit(): void {
  console.log('Generating p50k_edit (reuses p50k_base vocab)...');

  const content = `/**
 * Generated re-export for p50k_edit encoding.
 *
 * p50k_edit uses the same vocabulary as p50k_base,
 * just with different special tokens (handled separately).
 *
 * DO NOT EDIT - This file is auto-generated by scripts/codegen/encodings.ts
 */

export { VOCAB } from './p50k_base.js';
`;

  const outputPath = join(OUTPUT_DIR, 'p50k_edit.ts');
  writeFileSync(outputPath, content, 'utf-8');
  console.log(`  Written to ${outputPath}`);
}

/**
 * Generate o200k_harmony module (reuses o200k_base vocab).
 */
function generateO200kHarmony(): void {
  console.log('Generating o200k_harmony (reuses o200k_base vocab)...');

  const content = `/**
 * Generated re-export for o200k_harmony encoding.
 *
 * o200k_harmony uses the same vocabulary as o200k_base,
 * just with different special tokens (handled separately).
 *
 * DO NOT EDIT - This file is auto-generated by scripts/codegen/encodings.ts
 */

export { VOCAB } from './o200k_base.js';
`;

  const outputPath = join(OUTPUT_DIR, 'o200k_harmony.ts');
  writeFileSync(outputPath, content, 'utf-8');
  console.log(`  Written to ${outputPath}`);
}

/**
 * Generate index file that exports all encodings.
 */
function generateIndex(): void {
  console.log('Generating index...');

  const content = `/**
 * Generated index for encoding vocabularies.
 *
 * DO NOT EDIT - This file is auto-generated by scripts/codegen/encodings.ts
 */

export { VOCAB as R50K_BASE_VOCAB } from './r50k_base.js';
export { VOCAB as P50K_BASE_VOCAB } from './p50k_base.js';
export { VOCAB as P50K_EDIT_VOCAB } from './p50k_edit.js';
export { VOCAB as CL100K_BASE_VOCAB } from './cl100k_base.js';
export { VOCAB as O200K_BASE_VOCAB } from './o200k_base.js';
export { VOCAB as O200K_HARMONY_VOCAB } from './o200k_harmony.js';
`;

  const outputPath = join(OUTPUT_DIR, 'index.ts');
  writeFileSync(outputPath, content, 'utf-8');
  console.log(`  Written to ${outputPath}`);
}

/**
 * Main entry point.
 */
async function main(): Promise<void> {
  console.log('=== Encoding Codegen ===\n');

  // Ensure output directory exists
  mkdirSync(OUTPUT_DIR, { recursive: true });

  // Process each encoding
  for (const encoding of Object.keys(ENCODINGS) as EncodingName[]) {
    await processEncoding(encoding);
    console.log('');
  }

  // Generate derivative encodings
  generateP50kEdit();
  console.log('');

  generateO200kHarmony();
  console.log('');

  // Generate index
  generateIndex();

  console.log('\n=== Done ===');
}

main().catch((error) => {
  console.error('Error:', error);
  process.exit(1);
});
